- name: Removes all anonymous user accounts mysql
  mysql_user:
    name: ''
    host_all: yes
    state: absent
- name: Add mysql db
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
- name: Add mysql user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass}}"
    priv: '{{ mysql_db }}.*:ALL'
    state: present